/**
 * Export engine — CSV builder + print-to-PDF utility
 * All functions run client-side only (no server dependency).
 */

// ─── CSV ──────────────────────────────────────────────────────────────────────

/**
 * Escape a CSV cell value.
 */
function csvCell(value: unknown): string {
  const str = value === null || value === undefined ? "" : String(value);
  // Wrap in quotes if contains comma, newline, or double-quote
  if (str.includes(",") || str.includes("\n") || str.includes('"')) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

/**
 * Convert an array of objects to a CSV string.
 * Column order follows the keys of the first row.
 */
export function objectsToCsv(rows: Record<string, unknown>[]): string {
  if (rows.length === 0) return "";
  const headers = Object.keys(rows[0]);
  const lines = [
    headers.map(csvCell).join(","),
    ...rows.map((row) => headers.map((h) => csvCell(row[h])).join(",")),
  ];
  return lines.join("\n");
}

/**
 * Trigger a browser download of a CSV string.
 */
export function downloadCsv(csv: string, filename: string) {
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename.endsWith(".csv") ? filename : `${filename}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

/**
 * One-shot: convert records to CSV and download.
 */
export function exportCsv(rows: Record<string, unknown>[], filename: string) {
  downloadCsv(objectsToCsv(rows), filename);
}

// ─── PDF (print-to-PDF) ───────────────────────────────────────────────────────

export interface PdfOptions {
  title?: string;
  subtitle?: string;
  /** CSS styles injected into the print iframe */
  extraStyles?: string;
}

/**
 * Open a hidden print-iframe with the given HTML content.
 * The user's browser print dialog appears; "Save as PDF" exports as PDF.
 */
export function printHtml(htmlBody: string, opts: PdfOptions = {}) {
  const { title = "Export", subtitle = "", extraStyles = "" } = opts;

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>${title}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: "Georgia", serif; font-size: 11pt; color: #111; background: #fff; padding: 32px 40px; }
    h1 { font-size: 18pt; font-weight: 700; margin-bottom: 4px; }
    .subtitle { font-size: 10pt; color: #666; margin-bottom: 24px; }
    table { width: 100%; border-collapse: collapse; margin-top: 12px; }
    th { background: #111; color: #fff; font-size: 9pt; font-weight: 600; padding: 7px 10px; text-align: left; }
    td { padding: 6px 10px; border-bottom: 1px solid #e5e5e5; font-size: 10pt; vertical-align: top; }
    tr:nth-child(even) td { background: #f8f8f8; }
    .badge { display: inline-block; padding: 1px 7px; border-radius: 99px; font-size: 9pt; font-weight: 600; }
    .footer { margin-top: 32px; font-size: 9pt; color: #999; border-top: 1px solid #ddd; padding-top: 12px; }
    @media print { body { padding: 0; } }
    ${extraStyles}
  </style>
</head>
<body>
  <h1>${title}</h1>
  ${subtitle ? `<div class="subtitle">${subtitle}</div>` : ""}
  ${htmlBody}
  <div class="footer">Generated by Perfume Intelligence Lab · ${new Date().toLocaleDateString()}</div>
</body>
</html>`;

  const iframe = document.createElement("iframe");
  iframe.style.cssText = "position:fixed;top:-9999px;left:-9999px;width:1px;height:1px;border:none;";
  document.body.appendChild(iframe);
  const doc = iframe.contentDocument ?? iframe.contentWindow?.document;
  if (!doc) return;
  doc.open();
  doc.write(html);
  doc.close();
  iframe.contentWindow?.focus();
  setTimeout(() => {
    iframe.contentWindow?.print();
    setTimeout(() => document.body.removeChild(iframe), 2000);
  }, 400);
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Build an HTML <table> from rows + optional column label map. */
export function buildHtmlTable(
  rows: Record<string, unknown>[],
  columns?: { key: string; label: string }[]
): string {
  if (rows.length === 0) return "<p>No data.</p>";
  const cols = columns ?? Object.keys(rows[0]).map((k) => ({ key: k, label: k }));
  const thead = `<thead><tr>${cols.map((c) => `<th>${c.label}</th>`).join("")}</tr></thead>`;
  const tbody = `<tbody>${rows
    .map((row) => `<tr>${cols.map((c) => `<td>${row[c.key] ?? "—"}</td>`).join("")}</tr>`)
    .join("")}</tbody>`;
  return `<table>${thead}${tbody}</table>`;
}
